### ISSUE TITLE
POGO should generate code that doesn't require "using namespace std"

### ISSUE THREAD

**Issue by beenje** [tango-controls/pogo#101]
It's possible to compile `cppTango` with `TANGO_USE_USING_NAMESPACE=OFF`.
POGO should generate code with `std::` prefix when required.

**Comment by t-b** [comment]
cppTango developer here. I would say that pogo should unconditionally use full namespace specifications like `std::`. The reason we have the compile time switch in cppTango is for backwards compatibility only.
