### ISSUE TITLE
Provide build instructions/docker image to use Pogo HEAD version

### ISSUE THREAD

**Issue by t-b** [tango-controls/pogo#107]
For TangoTest, and also other stock device servers, it would be nice if we could use pogo as part of CI. Therefore it would be nice if there was a Dockerfile we could use to get the latest pogo version.

Or maybe having build instructions for pogo would suffice for now. Sorry I'm not a java person.

**Comment by dlacoste-esrf** [comment]
Hi,
I created a branch to build pogo in a docker environment ()https://github.com/dlacoste-esrf/pogo/tree/dockerize) you can try it. To build:

```bash
cd docker
make
```

Then it's a bit tricky to start it, as it is an X11 app, so you have to pass your display to the docker environment and so on, I used x11docker, it saves some trouble…
A pogorc file is missing as well, I could provide a generic one, but it might not be necessary… 

Let me know how it goes.

Cheers

**Comment by t-b** [comment]
The above comment was me.
