### ISSUE TITLE
Generates inefficient code for enum images due to misplaced protected region start

### ISSUE THREAD

**Issue by t-b** [tango-controls/pogo#113]
Using the attached xmi file
[TangoTest.xmi.orig.zip](https://github.com/tango-controls/pogo/files/6279933/TangoTest.xmi.orig.zip)

the latest version of pogo generates the following c++ code for writeable enum images

```cpp
void TangoTest::write_enum_image(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TangoTest::write_enum_image(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve number of write values
	int	w_length = attr.get_write_value_length();

	//	Retrieve pointer on write values (Do not delete !)
	const short *w_val;
	attr.get_write_value(w_val);
	enum_imageEnum enum_val[w_length];
	for (int i=0 ; i<w_length ; i++)  enum_val[i]=(enum_imageEnum) w_val[i];
	/*----- PROTECTED REGION ID(TangoTest::write_enum_image) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	TangoTest::write_enum_image
}
```

I would have expected the code to be 

```cpp
void TangoTest::write_enum_image(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "TangoTest::write_enum_image(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve number of write values
	int	w_length = attr.get_write_value_length();

	//	Retrieve pointer on write values (Do not delete !)
	const short *w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(TangoTest::write_enum_image) ENABLED START -----*/

	enum_imageEnum enum_val[w_length];
	for (int i=0 ; i<w_length ; i++)  enum_val[i]=(enum_imageEnum) w_val[i];

	/*----- PROTECTED REGION END -----*/	//	TangoTest::write_enum_image
}
```
as the copying into enum_val might be a usable suggestion but should not be generated and enforced code.

This is also more in line what it does for other images, see also https://gitlab.com/tango-controls/TangoTest/-/blob/main/TangoTest.cpp#L2971.

**Comment by dlacoste-esrf** [comment]
why not... Are you speaking specifically of enum images or should we move it for images of any types, and even spectrum of any types (cause they will generate more or less the same code...) ?

**Comment by t-b** [comment]
The issue is that the generated code is for enum images different than compared to other image types. So I would like to have enum images behave the same compared to e.g. double images.

**Comment by dlacoste-esrf** [comment]
This is indeed specific to enum in images and spectrum as well, my first message is wrong.
It can be changed, the main issue I see here is I have no idea why it was added in the first place…
