### ISSUE TITLE
Pogo should be able to generate maven project for java tango classes

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/pogo#35]
Add maven project generation feature. This may replace any other project generation for java (IntelliJ IDEA for the moment of creation this ticket) as any modern java IDE supports maven.

Generated project must resolve all dependencies.

Reported by: Ingvord ( http://sf.net/u/ingvord )

Original Ticket: [tango-cs/feature-requests/106](https://sourceforge.net/p/tango-cs/feature-requests/106)

**Comment by Pascal-Verdier** [comment]
done
