### ISSUE TITLE
Support DevEnum in commands

### ISSUE THREAD

**Issue by josefcibulka** [tango-controls/pogo#40]
CppTango library now supports setting the list of enum values for the DevEnum input and output of Commands: https://github.com/tango-controls/cppTango/issues/351 So POGO could now support setting these lists the same way as it does for attributes of type DevEnum.

**Comment by ajoubertza** [comment]
For the PythonHL generation it would be better to create `IntEnum` classes and use those directly as the `dtype`.  See PyTango example [here](https://github.com/tango-controls/pytango/blob/19e4c5daf5916384b030b4fb1e373d72d1c0c0e7/examples/Clock/ClockDS.py#L46).
