### ISSUE TITLE
generated Makefile: Wrong comment for OUTPUT_DIR

### ISSUE THREAD

**Issue by t-b** [tango-controls/pogo#45]
Version: Tango 9.2.5a

A newly generated Makefiles has

```
#=============================================================================
# OUTPUT_DIR  is the directory which contains the build result.
# if not set, the standard location is :
#	- ./shlib if OUTPUT_TYPE is SHARED_LIB
#	- ./lib   if OUTPUT_TYPE is STATIC_LIB
#	- ./bin for others
#
#OUTPUT_DIR =
```

but looking at `/usr/local/share/pogo/preferences/tango.opt` gives

```
ifndef OUTPUT_DIR
ifeq ($(PROJECT_TYPE),DEVICE)
	OUTPUT_DIR= $(HOME)/DeviceServers
else
ifeq ($(PROJECT_TYPE),STATIC_LIB)
	OUTPUT_DIR= lib
else
ifeq ($(PROJECT_TYPE),SHARED_LIB)
	OUTPUT_DIR= lib
else
	OUTPUT_DIR= bin
endif
endif
endif
endif
```

so one of them is wrong.

**Comment by Pascal-Verdier** [comment]
You are right.
I will fix it in next release.

**Comment by t-b** [comment]
@Pascal-Verdier Is that already fixed?

**Comment by Pascal-Verdier** [comment]
I don't know.
It is not a Pogo problem, it is a distribution problem.
I will check the **tango.opt** file given with the distribution

**Comment by Pascal-Verdier** [comment]
Sorry.
I check the tango.opt file. It has not been modified in distribution
But the Makefile comment generated has been modified.
