### ISSUE TITLE
generated remove_xxx_dynamic_attribute() method assumes database is always used

### ISSUE THREAD

**Issue by mike-a-smith** [tango-controls/pogo#50]
Hello,

I found that for my device servers that don't use the database, the device crashes when calling the auto-generated remove_xxx_dynamic_attribute() method.

The reason is the first line in the method ( remove_attribute(attname, true); ) is called with two arguments which means the third argument of 'bool clean_db' defaults to true  In the body of remove_attribute the code tries to connect to the database.

The fix is to generate this line instead:  remove_attribute(attname, true, Tango::Util::instance()->_UseDb);

The clean_db argument will be false and database connection skipped.

Mike

**Comment by Pascal-Verdier** [comment]
Hi Mike
You are perfectly right.
It is now available in [Pogo-9.6-11](https://bintray.com/tango-controls/maven/download_file?file_path=org%2Ftango%2Ftools%2Fpogo%2Fgui%2FPogo%2F9.6.11%2FPogo-9.6.11.jar)

Thanks for your advice. Sorry for the delay.
Regards
Pascal
