### ISSUE TITLE
pogo pythonHL and read_attr_hardware dev_state dev_status

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pogo#55]
Is there any way to create `read_attr_hardware` `dev_state` `dev_status` with pogo in the pythonHL mode automatically or it should be created post generation?

**Comment by jkotan** [comment]
Hi,
Ah, I forgot about it. Thanks.
Is there any way to create `read_attr_hardware`  as well or I should put it somewhere in unprotected part by myself?

**Comment by NexeyaSGara** [comment]
Hi, for the moment, we don't have any selector to generate or not,the read_attr_hardware code for the pythonHL.

So your best shot is to write it by your self.

Don't forget that if you put your code in unprotected régions and that you regenerate from Pogo, you will lost your modifications.

I suggest that you use the first protected region of the generated class : 

 # PROTECTED REGION ID(MyDeviceClass.class_variable) ENABLED START #
dev_read_attr_hardware():
    # PROTECTED REGION END #    //  MyDeviceClass.class_variable

**Comment by jkotan** [comment]
Thanks.
