### ISSUE TITLE
additional files treatment in CMakeLists.txt

### ISSUE THREAD

**Issue by fatboy92** [tango-controls/pogo#57]
Although the xmi file seems keeping the right list of additional files, the CMakeLists.txt file transforms them all into cpp file, while some of my files are pure C files. 
At the same time, one of them is in a sub directory and while the xmi file keeps the directory name, the CMakeLists.txt file no longer carries that directory path.

**Comment by Pascal-Verdier** [comment]
Fixed in new release Pogo-9.6.20
