### ISSUE TITLE
Cannot regenerate Pogo package

### ISSUE THREAD

**Issue by Pascal-Verdier** [tango-controls/pogo#58]
Since weeks, I cannot regenerate Pogo jar file.
Maven crashes with 
`Error injecting constructor, com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package`
I tried to find help on forums but it was not really useful.
An idea ? Someone ?

**Comment by bourtemb** [comment]
The workaround in this [comment](https://github.com/eclipse/xtext/issues/1231#issuecomment-449444931) seems to work.

**Comment by Pascal-Verdier** [comment]
Thanks a lot for this workaround.
