### ISSUE TITLE
Support external template generator files

### ISSUE THREAD

**Issue by ajoubertza** [tango-controls/pogo#62]
Different projects have different coding standards, and may use different testing frameworks (e.g. nosetest vs pytest for Python).  It will be difficult for Pogo's generated output to match the needs of all users, thus the suggestion of allowing external templates.

Currently the code templates are compiled into the Java jar file, so the only way to edit them is to recompile from source, which is hard for non-Java developers.  It would be beneficial if external files could be used as template generators, at least from the command line:

E.g. `pogo -src MyDevice.xmi -generator MyPythonDeviceHL.xtend`

As xtend is just a Java dialect, it will still need to be compiled, so not sure how we would deal with that.  Maybe this idea just isn't feasible?

**Comment by Pascal-Verdier** [comment]
Good idea. But yes, I think it is not feasible
