### ISSUE TITLE
9.3.4-rc2: Does not finish load screen

### ISSUE THREAD

**Issue by t-b** [tango-controls/pogo#83]
pogo 9.6.23:

Using java 8u242-b04-1 on debian unstable with tango source distribution 9.3.4-rc2 and doing

```
pogo Database.xmi
```

the load screen never finishes. It goes all the way up to 100% and then restarts at zero. 
![Debian unstable 64bit-2020-01-10-19-03-16](https://user-images.githubusercontent.com/1185677/72175626-d81fb600-33dc-11ea-9d0a-4c215c798571.png)

**Comment by t-b** [comment]
Still present with pogo 9.6.27 from TDS 9.3.4-rc6.

**Comment by bourtemb** [comment]
Just tried with Pogo 9.6.31 (We should use that one by the way for the coming Source Distribution) with following java version:

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

@t-b, do you get this problem systematically?
Do you know what is the ATK version you are using?

**Comment by bourtemb** [comment]
> Just tried with Pogo 9.6.31 (We should use that one by the way for the coming Source Distribution) with following java 

Oops, sorry, I just saw you already updated Pogo to 9.6.31 in tango source distribution 9.3.4-rc7. Thanks for that.

**Comment by t-b** [comment]
@bourtemb Yes the new rc has 9.6.31 already. I'll retest with a newer pogo version.

**Comment by t-b** [comment]
Still seeing that here:

![grafik](https://user-images.githubusercontent.com/1185677/92723529-7a77ab00-f369-11ea-95ce-f6f087aca63b.png)

```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode) 
```
I'm seeing it with TangoTest.xmi as well.

**Comment by t-b** [comment]
@bourtemb Unfortunately I can't share the VM, as it contains a lot of internal data. Should I setup a fresh one and try to reproduce the bug? I can send you that then.

**Comment by bourtemb** [comment]
> @bourtemb Unfortunately I can't share the VM, as it contains a lot of internal data. Should I setup a fresh one and try to reproduce the bug? I can send you that then.

@t-b, that could be very helpful indeed, unless @Pascal-Verdier has some other suggestions?

**Comment by Pascal-Verdier** [comment]
No other suggestion.
In my environment, I cannot reproduce.

**Comment by t-b** [comment]
I've setup a new debian unstable VM. With java-8u271. And recompiled TSD 9.3.4. And the problem is gone.

Thanks both.
