### ISSUE TITLE
PythonHL must not include DeviceMeta as metaclass

### ISSUE THREAD

**Issue by ajoubertza** [tango-controls/pogo#85]
Since PyTango 9.2.1 (Jan 2017) it is not longer necessary to include `__metaclass__ = DeviceMeta` in the class inheriting from `Device`.  Also, this isn't how metaclasses are specified in Python 3.   The PyTango PR that removed this requirement is [here](https://github.com/tango-controls/pytango/pull/90).

Pogo should remove it from here:
https://github.com/tango-controls/pogo/blob/5d6375127ee6b0d9109ba21b7a61f5dd8811a290/fr.esrf.tango.generator.xtend/src/fr/esrf/tango/pogo/generator/python/PythonDeviceHL.xtend#L144

And from here:
https://github.com/tango-controls/pogo/blob/6537cb9484f8a31f2f3d4f6130846dbb68652e43/fr.esrf.tango.generator.xtend/src/fr/esrf/tango/pogo/generator/python/PythonDeviceHL.xtend#L212

**Comment by KrystianKedron** [comment]
@mesnehal , @dlacoste-esrf I think we can close this issue ;)
