### ISSUE TITLE
Pogo re-generates Python method delete_device(self) when theres exists a modified one

### ISSUE THREAD

**Issue by tjuerges** [tango-controls/pogo#96]
Here's my situation:
```
    def delete_device(self):
        # PROTECTED REGION ID(Crossecho.delete_device) ENABLED START #
        self.client.close_session()
        self.client.close_secure_channel()
        # PROTECTED REGION END #    //  Crossecho.delete_device
```

And whenever I re-run Pogo, re-create the source code, I end up with another method delete_device(self) right next to the original one:
```
    def delete_device(self):
        # PROTECTED REGION ID(Crossecho.delete_device) ENABLED START #
        self.client.close_session()
        self.client.close_secure_channel()
        # PROTECTED REGION END #    //  Crossecho.delete_device

    def delete_device(self):
        # PROTECTED REGION ID(Crossecho.delete_device) ENABLED START #
        pass
        # PROTECTED REGION END #    //  Crossecho.delete_device
```
I am still new to the Tango universe and therefore I suppose I could have been missing something?

Cheers
Thomas

**Comment by ajoubertza** [comment]
@mesnehal Could you please look into this and provide some help?

**Comment by mesnehal** [comment]
Yes @ajoubertz. I will check and see if I can do something.

**Comment by mesnehal** [comment]
@tjuerges Which version of POGO are you using?  I am not able to re-generate the issue with POGO version [9.6.31](https://bintray.com/tango-controls/maven/Pogo/9.6.31#),
Could please confirm if the issue occurs with the latest POGO?

**Comment by tjuerges** [comment]
@mesnehal I am using SKA's Docker images (https://gitlab.com/ska-telescope/ska-docker).  How would I go about to update Pogo there, please?

@bourtemb Do you still want me to file a ticket in Pogo's issues?

**Comment by bourtemb** [comment]
> @bourtemb Do you still want me to file a ticket in Pogo's issues?

@tjuerges , this is no longer needed. I already transferred your issues to the Pogo repository (we are in pogo repo now).

**Comment by tjuerges** [comment]
I just tried it out with Pogo 9.6.31.  Unfortunately the error is still there.
