### ISSUE TITLE
Pogo creates illegal Python code for DevUlong64 properties

### ISSUE THREAD

**Issue by tjuerges** [tango-controls/pogo#97]
Hi Tango gurus,

Here's what happened:
I created a DevULong64 property in my device, then let Pogo create the code.  Unfortunately, when I ran the code I was greeted with a syntax error that was caused by the code that Pogo: had just created:
```
     OPC_time_out = device_property(
        dtype=, default_value=1000
    )
```

When I then, in Pogo, modified the property type from DevULong64 to DevULong and generated the code, all was good again:
```
    OPC_time_out = device_property(
        dtype='uint', default_value=1000
    )
```

But since I initially chose DevULong64 as the data type for my property, I suppose that there is a bug in Pogo.

Cheers
Thomas

**Comment by ajoubertza** [comment]
@mesnehal Another one for you, please.

@tjuerges Please confirm the Pogo version you are using.  And check for latest version here:  https://bintray.com/tango-controls/maven/Pogo/_latestVersion

Download jar file from the _Files_ tab.  9.6.31 is latest a time of writing.

**Comment by tjuerges** [comment]
@ajoubertza I am using Pogo from within the SKA Docker images. So I suppose I change the Pogo jar from inside the Pogo container (tango-pogo)?

**Comment by ajoubertza** [comment]
Yes, you can [change](https://gitlab.com/ska-telescope/ska-docker/-/blob/72133303/docker/tango/tango-pogo/Dockerfile#L22-25) inside the image.  Or pull the latest:
`docker pull nexus.engageska-portugal.pt/ska-docker/tango-pogo:9.6.31`

**Comment by tjuerges** [comment]
I just tried it out with Pogo 9.6.31.  Unfortunately ehe error is still there.

**Comment by dlacoste-esrf** [comment]
I tried to fix this one, I can put a value but I have no idea which one...
I followed the documentation (https://pytango.readthedocs.io/en/stable/data_types.html#pytango-data-types)
except for arrays where it becomes quite complicated to understand.
So if anyone fluent in pythonHL could have a look it would be nice. I pushed the modifications in the branch fix-97-proprty-dtype

**Comment by dlacoste-esrf** [comment]
And what about the commands definitions as well ?
